/* Company directory data and rendering */
'use strict';

var SHARED_SOURCES = {
    enr: 'https://www.enr.com/toplists/2025-Top-400-Contractors-1-preview',
    sec: 'https://www.sec.gov/edgar/searchedgar/companysearch',
    macrotrends: 'https://www.macrotrends.net'
};

var NORTH_AMERICA_LEADERS = [
    { name: 'Quanta Services', nameUrl: 'https://www.quantaservices.com', hq: 'Houston, TX', hqUrl: 'https://www.quantaservices.com/about', coverage: 'U.S. + Canada', coverageUrl: 'https://www.quantaservices.com/operations', segment: 'Electric, pipeline, utility infrastructure', segmentUrl: 'https://www.quantaservices.com/services', ownership: 'Public (NYSE: PWR)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$22.8B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PWR/quanta-services/revenue', notes: 'Largest U.S.-listed specialty infrastructure contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'Bechtel', nameUrl: 'https://www.bechtel.com', hq: 'Reston, VA', hqUrl: 'https://www.bechtel.com/about-us/', coverage: 'North America + global', coverageUrl: 'https://www.bechtel.com/projects/', segment: 'Heavy civil, energy, transportation', segmentUrl: 'https://www.bechtel.com/capabilities/', ownership: 'Private', ownershipUrl: 'https://www.bechtel.com/about-us/governance/', revenue: '$20B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Consistently at top of ENR rankings', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Kiewit', nameUrl: 'https://www.kiewit.com', hq: 'Omaha, NE', hqUrl: 'https://www.kiewit.com/about-us', coverage: 'U.S. + Canada', coverageUrl: 'https://www.kiewit.com/markets/transportation', segment: 'Heavy civil, mining, power, water', segmentUrl: 'https://www.kiewit.com/markets', ownership: 'Employee-owned private', ownershipUrl: 'https://www.kiewit.com/about-us/culture', revenue: '$14B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Core NA heavy civil benchmark', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'Fluor', nameUrl: 'https://www.fluor.com', hq: 'Irving, TX', hqUrl: 'https://www.fluor.com/about-fluor', coverage: 'North America + global', coverageUrl: 'https://www.fluor.com/projects', segment: 'Industrial, infrastructure, energy', segmentUrl: 'https://www.fluor.com/markets', ownership: 'Public (NYSE: FLR)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$15.6B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/FLR/fluor/revenue', notes: 'Major EPC and infrastructure contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'EMCOR Group', nameUrl: 'https://www.emcorgroup.com', hq: 'Norwalk, CT', hqUrl: 'https://www.emcorgroup.com/about-us/', coverage: 'U.S. + Canada', coverageUrl: 'https://www.emcorgroup.com/our-companies/', segment: 'Mechanical, electrical, facilities', segmentUrl: 'https://www.emcorgroup.com/services/', ownership: 'Public (NYSE: EME)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$14.6B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/EME/emcor-group/revenue', notes: 'Top publicly traded specialty construction firm', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Jacobs', nameUrl: 'https://www.jacobs.com', hq: 'Dallas, TX', hqUrl: 'https://www.jacobs.com/about', coverage: 'North America + global', coverageUrl: 'https://www.jacobs.com/projects', segment: 'Water, transportation, defense infrastructure', segmentUrl: 'https://www.jacobs.com/solutions', ownership: 'Public (NYSE: J)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$11.5B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/J/jacobs-solutions/revenue', notes: 'Large infrastructure design-build and program manager', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Primoris', nameUrl: 'https://www.primoriscorp.com', hq: 'Dallas, TX', hqUrl: 'https://www.primoriscorp.com/about/', coverage: 'U.S. + selected Canada', coverageUrl: 'https://www.primoriscorp.com/markets/', segment: 'Utilities, pipeline, civil construction', segmentUrl: 'https://www.primoriscorp.com/services/', ownership: 'Public (NASDAQ: PRIM)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$5.7B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PRIM/primoris-services/revenue', notes: 'Key underground and utility benchmark', notesUrl: SHARED_SOURCES.enr, type: ['underground', 'heavy-civil'] },
    { name: 'PCL Construction', nameUrl: 'https://www.pcl.com', hq: 'Edmonton, AB', hqUrl: 'https://www.pcl.com/ca/en/who-we-are', coverage: 'Canada + U.S.', coverageUrl: 'https://www.pcl.com/ca/en/locations', segment: 'Buildings + civil infrastructure', segmentUrl: 'https://www.pcl.com/ca/en/what-we-do', ownership: 'Employee-owned private', ownershipUrl: 'https://www.pcl.com/ca/en/who-we-are', revenue: '$9B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'One of the largest North American contractors', notesUrl: SHARED_SOURCES.enr, type: ['gc', 'heavy-civil'] },
    { name: 'Aecon Group', nameUrl: 'https://www.aecon.com', hq: 'Toronto, ON', hqUrl: 'https://www.aecon.com/about', coverage: 'Canada + U.S.', coverageUrl: 'https://www.aecon.com/what-we-do', segment: 'Civil, utilities, concessions', segmentUrl: 'https://www.aecon.com/what-we-do/construction', ownership: 'Public (TSX: ARE)', ownershipUrl: 'https://www.aecon.com/investors', revenue: 'C$4.3B (2024)', revenueUrl: 'https://www.aecon.com/investors/financial-reports', notes: 'Large Canadian infrastructure platform', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] }
];

var UNITED_STATES_LEADERS = [
    { name: 'Quanta Services', nameUrl: 'https://www.quantaservices.com', hq: 'Houston, TX', hqUrl: 'https://www.quantaservices.com/about', coverage: 'United States', coverageUrl: 'https://www.quantaservices.com/operations', segment: 'T&D, pipeline, telecom, civil utilities', segmentUrl: 'https://www.quantaservices.com/services', ownership: 'Public (NYSE: PWR)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$22.8B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PWR/quanta-services/revenue', notes: 'Largest U.S. infrastructure specialty company', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'Turner Construction', nameUrl: 'https://www.turnerconstruction.com', hq: 'New York, NY', hqUrl: 'https://www.turnerconstruction.com/corporate', coverage: 'United States', coverageUrl: 'https://www.turnerconstruction.com/offices', segment: 'General building construction', segmentUrl: 'https://www.turnerconstruction.com/market-segments', ownership: 'Subsidiary (HOCHTIEF)', ownershipUrl: 'https://www.hochtief.com', revenue: '$16B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Largest building GC in U.S. market', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Kiewit', nameUrl: 'https://www.kiewit.com', hq: 'Omaha, NE', hqUrl: 'https://www.kiewit.com/about-us', coverage: 'United States', coverageUrl: 'https://www.kiewit.com/markets', segment: 'Heavy civil + industrial', segmentUrl: 'https://www.kiewit.com/markets/transportation', ownership: 'Employee-owned private', ownershipUrl: 'https://www.kiewit.com/about-us/culture', revenue: '$14B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Top U.S. heavy civil contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Fluor', nameUrl: 'https://www.fluor.com', hq: 'Irving, TX', hqUrl: 'https://www.fluor.com/about-fluor', coverage: 'United States + global projects', coverageUrl: 'https://www.fluor.com/projects', segment: 'Industrial + infrastructure EPC', segmentUrl: 'https://www.fluor.com/markets', ownership: 'Public (NYSE: FLR)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$15.6B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/FLR/fluor/revenue', notes: 'Core U.S. infrastructure and industrial prime', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Jacobs', nameUrl: 'https://www.jacobs.com', hq: 'Dallas, TX', hqUrl: 'https://www.jacobs.com/about', coverage: 'United States', coverageUrl: 'https://www.jacobs.com/projects', segment: 'Water + transportation + federal', segmentUrl: 'https://www.jacobs.com/solutions', ownership: 'Public (NYSE: J)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$11.5B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/J/jacobs-solutions/revenue', notes: 'Large U.S. owner-side infrastructure partner', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'AECOM', nameUrl: 'https://aecom.com', hq: 'Dallas, TX', hqUrl: 'https://aecom.com/about-us', coverage: 'United States + global', coverageUrl: 'https://aecom.com/projects', segment: 'Infrastructure engineering and CM', segmentUrl: 'https://aecom.com/services', ownership: 'Public (NYSE: ACM)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$14.4B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/ACM/aecom/revenue', notes: 'Large U.S. infrastructure delivery platform', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'EMCOR Group', nameUrl: 'https://www.emcorgroup.com', hq: 'Norwalk, CT', hqUrl: 'https://www.emcorgroup.com/about-us/', coverage: 'United States', coverageUrl: 'https://www.emcorgroup.com/our-companies/', segment: 'Mechanical + electrical', segmentUrl: 'https://www.emcorgroup.com/services/', ownership: 'Public (NYSE: EME)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$14.6B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/EME/emcor-group/revenue', notes: 'Public market benchmark for MEP construction', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Primoris', nameUrl: 'https://www.primoriscorp.com', hq: 'Dallas, TX', hqUrl: 'https://www.primoriscorp.com/about/', coverage: 'United States', coverageUrl: 'https://www.primoriscorp.com/markets/', segment: 'Underground utilities + pipeline', segmentUrl: 'https://www.primoriscorp.com/services/', ownership: 'Public (NASDAQ: PRIM)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$5.7B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PRIM/primoris-services/revenue', notes: 'Public proxy for underground utility activity', notesUrl: SHARED_SOURCES.enr, type: ['underground'] },
    { name: 'Granite Construction', nameUrl: 'https://www.graniteconstruction.com', hq: 'Watsonville, CA', hqUrl: 'https://www.graniteconstruction.com/about-us', coverage: 'United States', coverageUrl: 'https://www.graniteconstruction.com/projects', segment: 'Transportation + water + tunnels', segmentUrl: 'https://www.graniteconstruction.com/services', ownership: 'Public (NYSE: GVA)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$4.3B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/GVA/granite-construction/revenue', notes: 'Heavy civil public benchmark', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'Bluelight Machines', nameUrl: 'https://bluelightmachines.com/', hq: 'Pittsburgh, PA', hqUrl: 'https://www.linkedin.com/in/zhangr/', coverage: 'United States + Australia + global deployments', coverageUrl: 'https://bluelightmachines.com/', segment: 'Autonomous compaction retrofit systems for CAT and Dynapac rollers', segmentUrl: 'https://bluelightmachines.com/', ownership: 'Private', ownershipUrl: 'https://bluelightmachines.com/', revenue: 'Private', revenueUrl: 'https://bluelightmachines.com/', notes: 'Autonomy platform with 200+ sites and 1B+ sq ft rolled', notesUrl: 'https://bluelightmachines.com/', type: ['heavy-civil', 'underground'] }
];

var STATE_LEADERS = [
    { name: 'Granite Construction', nameUrl: 'https://www.graniteconstruction.com', hq: 'Watsonville, CA', hqUrl: 'https://www.graniteconstruction.com/about-us', coverage: 'California', coverageUrl: 'https://www.graniteconstruction.com/locations', segment: 'Heavy civil + transportation', segmentUrl: 'https://www.graniteconstruction.com/services', ownership: 'Public (NYSE: GVA)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$4.3B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/GVA/granite-construction/revenue', notes: 'Large CA heavy-civil platform', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Hensel Phelps', nameUrl: 'https://www.henselphelps.com', hq: 'Greeley, CO', hqUrl: 'https://www.henselphelps.com/about/', coverage: 'Colorado', coverageUrl: 'https://www.henselphelps.com/projects/', segment: 'General building + infrastructure', segmentUrl: 'https://www.henselphelps.com/markets/', ownership: 'Employee-owned private', ownershipUrl: 'https://www.henselphelps.com/careers/', revenue: '$5B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Largest Colorado-based contractor by scale', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Quanta Services', nameUrl: 'https://www.quantaservices.com', hq: 'Houston, TX', hqUrl: 'https://www.quantaservices.com/about', coverage: 'Texas', coverageUrl: 'https://www.quantaservices.com/operations', segment: 'Utility + energy infrastructure', segmentUrl: 'https://www.quantaservices.com/services', ownership: 'Public (NYSE: PWR)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$22.8B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PWR/quanta-services/revenue', notes: 'Texas-based infrastructure giant', notesUrl: SHARED_SOURCES.enr, type: ['underground', 'heavy-civil'] },
    { name: 'Turner Construction', nameUrl: 'https://www.turnerconstruction.com', hq: 'New York, NY', hqUrl: 'https://www.turnerconstruction.com/corporate', coverage: 'New York', coverageUrl: 'https://www.turnerconstruction.com/offices', segment: 'Commercial + mission critical', segmentUrl: 'https://www.turnerconstruction.com/market-segments', ownership: 'Subsidiary (HOCHTIEF)', ownershipUrl: 'https://www.hochtief.com', revenue: '$16B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Largest NY-headquartered builder by volume', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Walsh Group', nameUrl: 'https://www.walshgroup.com', hq: 'Chicago, IL', hqUrl: 'https://www.walshgroup.com/about', coverage: 'Illinois', coverageUrl: 'https://www.walshgroup.com/projects', segment: 'Civil + transportation + water', segmentUrl: 'https://www.walshgroup.com/capabilities', ownership: 'Private', ownershipUrl: 'https://www.walshgroup.com/about', revenue: '$7B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Largest private Illinois heavy-civil contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Sundt Construction', nameUrl: 'https://www.sundt.com', hq: 'Tempe, AZ', hqUrl: 'https://www.sundt.com/about/', coverage: 'Arizona', coverageUrl: 'https://www.sundt.com/locations/', segment: 'Civil + industrial + building', segmentUrl: 'https://www.sundt.com/services/', ownership: 'ESOP', ownershipUrl: 'https://www.sundt.com/about/', revenue: '$2B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Largest AZ employee-owned contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'gc'] },
    { name: 'Las Vegas Paving', nameUrl: 'https://www.lasvegaspaving.com', hq: 'Las Vegas, NV', hqUrl: 'https://www.lasvegaspaving.com/about', coverage: 'Nevada', coverageUrl: 'https://www.lasvegaspaving.com/operations', segment: 'Roadway + heavy civil', segmentUrl: 'https://www.lasvegaspaving.com', ownership: 'Private', ownershipUrl: 'https://www.lasvegaspaving.com/about', revenue: '$1B (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Major Nevada transportation contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Brasfield & Gorrie', nameUrl: 'https://www.brasfieldgorrie.com', hq: 'Birmingham, AL', hqUrl: 'https://www.brasfieldgorrie.com/about-us/', coverage: 'Alabama', coverageUrl: 'https://www.brasfieldgorrie.com/projects/', segment: 'Commercial + industrial construction', segmentUrl: 'https://www.brasfieldgorrie.com/services/', ownership: 'Private', ownershipUrl: 'https://www.brasfieldgorrie.com/about-us/', revenue: '$5B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Largest AL-headquartered builder by ENR scale', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Balfour Beatty US', nameUrl: 'https://www.balfourbeattyus.com', hq: 'Charlotte, NC', hqUrl: 'https://www.balfourbeattyus.com/about/', coverage: 'North Carolina', coverageUrl: 'https://www.balfourbeattyus.com/projects/', segment: 'Building + civil + federal', segmentUrl: 'https://www.balfourbeattyus.com/services/', ownership: 'Public parent (LSE: BBY)', ownershipUrl: 'https://www.balfourbeatty.com/investors/', revenue: '$4B+ U.S. (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Large NC-based U.S. contractor', notesUrl: SHARED_SOURCES.enr, type: ['gc', 'heavy-civil'] },
    { name: 'Mortenson', nameUrl: 'https://www.mortenson.com', hq: 'Minneapolis, MN', hqUrl: 'https://www.mortenson.com/company', coverage: 'Minnesota', coverageUrl: 'https://www.mortenson.com/projects', segment: 'Energy, sports, mission critical', segmentUrl: 'https://www.mortenson.com/markets', ownership: 'Private', ownershipUrl: 'https://www.mortenson.com/company', revenue: '$7B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Largest MN-based constructor by ENR volume', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Absher Construction', nameUrl: 'https://www.absherco.com', hq: 'Puyallup, WA', hqUrl: 'https://www.absherco.com/about/', coverage: 'Washington', coverageUrl: 'https://www.absherco.com/our-work/', segment: 'General building + public works', segmentUrl: 'https://www.absherco.com/services/', ownership: 'Private', ownershipUrl: 'https://www.absherco.com/about/', revenue: '$1B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Leading WA-headquartered contractor', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Big-D Construction', nameUrl: 'https://www.big-d.com', hq: 'Salt Lake City, UT', hqUrl: 'https://www.big-d.com/about', coverage: 'Utah', coverageUrl: 'https://www.big-d.com/locations', segment: 'General contractor + industrial', segmentUrl: 'https://www.big-d.com/services', ownership: 'Private', ownershipUrl: 'https://www.big-d.com/about', revenue: '$1B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'One of Utah\'s largest private builders', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Bluelight Machines', nameUrl: 'https://bluelightmachines.com/', hq: 'Pittsburgh, PA', hqUrl: 'https://www.linkedin.com/in/zhangr/', coverage: 'Pennsylvania', coverageUrl: 'https://bluelightmachines.com/', segment: 'Autonomous roller retrofit technology', segmentUrl: 'https://bluelightmachines.com/', ownership: 'Private', ownershipUrl: 'https://bluelightmachines.com/', revenue: 'Private', revenueUrl: 'https://bluelightmachines.com/', notes: 'PA-based autonomy company focused on compaction productivity and safety', notesUrl: 'https://bluelightmachines.com/', type: ['heavy-civil'] }
];

var UTAH_COMPANIES = [
    { name: 'Jacobsen Construction', nameUrl: 'https://www.jacobsenconstruction.com', hq: 'Salt Lake City, UT', hqUrl: 'https://www.jacobsenconstruction.com/about', coverage: 'Utah + Intermountain West', coverageUrl: 'https://www.jacobsenconstruction.com/projects', segment: 'General contractor', segmentUrl: 'https://www.jacobsenconstruction.com/markets', ownership: 'Private', ownershipUrl: 'https://www.jacobsenconstruction.com/about', revenue: '$1B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'One of Utah\'s biggest general contractors', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Big-D Construction', nameUrl: 'https://www.big-d.com', hq: 'Salt Lake City, UT', hqUrl: 'https://www.big-d.com/about', coverage: 'Utah + Southwest', coverageUrl: 'https://www.big-d.com/locations', segment: 'General contractor + industrial', segmentUrl: 'https://www.big-d.com/services', ownership: 'Private', ownershipUrl: 'https://www.big-d.com/about', revenue: '$1B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Utah HQ national-scale builder', notesUrl: SHARED_SOURCES.enr, type: ['gc'] },
    { name: 'Ralph L. Wadsworth Construction', nameUrl: 'https://www.ralphwadsworth.com', hq: 'Draper, UT', hqUrl: 'https://www.ralphwadsworth.com/about-us/', coverage: 'Utah + western U.S.', coverageUrl: 'https://www.ralphwadsworth.com/projects/', segment: 'Heavy civil, mining, structures', segmentUrl: 'https://www.ralphwadsworth.com/our-services/', ownership: 'Private', ownershipUrl: 'https://www.ralphwadsworth.com/about-us/', revenue: '$500M+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Major Utah heavy-civil platform', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Wadsworth Brothers Construction', nameUrl: 'https://www.wadsworthbrothers.com', hq: 'Draper, UT', hqUrl: 'https://www.wadsworthbrothers.com/about', coverage: 'Utah', coverageUrl: 'https://www.wadsworthbrothers.com/projects', segment: 'Heavy civil + underground utilities', segmentUrl: 'https://www.wadsworthbrothers.com/services', ownership: 'Private', ownershipUrl: 'https://www.wadsworthbrothers.com/about', revenue: '$200M-$400M (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Strong transportation + utility mix', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'Geneva Rock Products', nameUrl: 'https://www.genevarock.com', hq: 'Orem, UT', hqUrl: 'https://www.genevarock.com/about-us/', coverage: 'Utah', coverageUrl: 'https://www.genevarock.com/locations/', segment: 'Aggregate + paving + heavy civil', segmentUrl: 'https://www.genevarock.com/services/', ownership: 'Private', ownershipUrl: 'https://www.genevarock.com/about-us/', revenue: '$500M-$1B (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Vertically integrated Utah contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'W.W. Clyde & Co.', nameUrl: 'https://www.wwclyde.net', hq: 'Springville, UT', hqUrl: 'https://www.wwclyde.net/about', coverage: 'Utah + Mountain West', coverageUrl: 'https://www.wwclyde.net/projects', segment: 'Road + bridge + earthwork', segmentUrl: 'https://www.wwclyde.net/services', ownership: 'Private', ownershipUrl: 'https://www.wwclyde.net/about', revenue: '$300M-$600M (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Legacy Utah heavy-civil company', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] },
    { name: 'Ames Construction', nameUrl: 'https://www.amesconstruction.com', hq: 'Burnsville, MN (major UT ops)', hqUrl: 'https://www.amesconstruction.com/about', coverage: 'Utah + western U.S.', coverageUrl: 'https://www.amesconstruction.com/projects', segment: 'Heavy civil + underground', segmentUrl: 'https://www.amesconstruction.com/services', ownership: 'Private', ownershipUrl: 'https://www.amesconstruction.com/about', revenue: '$1B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Large non-UT HQ contractor active in Utah', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'Sundt Construction', nameUrl: 'https://www.sundt.com', hq: 'Tempe, AZ (UT operations)', hqUrl: 'https://www.sundt.com/about/', coverage: 'Mountain West + Southwest', coverageUrl: 'https://www.sundt.com/locations/', segment: 'Civil + industrial + building', segmentUrl: 'https://www.sundt.com/services/', ownership: 'ESOP', ownershipUrl: 'https://www.sundt.com/about/', revenue: '$2B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Large employee-owned contractor with Utah work', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'gc'] }
];

var MW_COMPANIES = [
    { name: 'Kiewit', nameUrl: 'https://www.kiewit.com', hq: 'Omaha, NE', hqUrl: 'https://www.kiewit.com/about-us', coverage: 'Mountain West + Canada', coverageUrl: 'https://www.kiewit.com/markets/transportation', segment: 'Heavy civil + industrial + underground', segmentUrl: 'https://www.kiewit.com/markets', ownership: 'Employee-owned private', ownershipUrl: 'https://www.kiewit.com/about-us/culture', revenue: '$14B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Regional megaproject leader', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'Granite Construction', nameUrl: 'https://www.graniteconstruction.com', hq: 'Watsonville, CA', hqUrl: 'https://www.graniteconstruction.com/about-us', coverage: 'Mountain West + Pacific', coverageUrl: 'https://www.graniteconstruction.com/locations', segment: 'Transportation + water + mining', segmentUrl: 'https://www.graniteconstruction.com/services', ownership: 'Public (NYSE: GVA)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$4.3B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/GVA/granite-construction/revenue', notes: 'Frequent DOT transportation prime', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'underground'] },
    { name: 'Sundt Construction', nameUrl: 'https://www.sundt.com', hq: 'Tempe, AZ', hqUrl: 'https://www.sundt.com/about/', coverage: 'Arizona + Utah + New Mexico', coverageUrl: 'https://www.sundt.com/locations/', segment: 'Civil + industrial + building', segmentUrl: 'https://www.sundt.com/services/', ownership: 'ESOP', ownershipUrl: 'https://www.sundt.com/about/', revenue: '$2B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Leading Southwest ESOP contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil', 'gc'] },
    { name: 'Achen-Gardner Construction', nameUrl: 'https://www.achengardner.com', hq: 'Maricopa, AZ', hqUrl: 'https://www.achengardner.com/about-us', coverage: 'Arizona + Southwest', coverageUrl: 'https://www.achengardner.com/projects', segment: 'Underground utility + roadway', segmentUrl: 'https://www.achengardner.com/services', ownership: 'ESOP', ownershipUrl: 'https://www.achengardner.com/about-us', revenue: '$300M+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Top Southwest underground specialist', notesUrl: SHARED_SOURCES.enr, type: ['underground', 'heavy-civil'] },
    { name: 'ESCO Construction', nameUrl: 'https://www.escoconstruction.com', hq: 'Meridian, ID', hqUrl: 'https://www.escoconstruction.com/about-us', coverage: 'Idaho + Mountain West', coverageUrl: 'https://www.escoconstruction.com/projects', segment: 'Underground + heavy civil', segmentUrl: 'https://www.escoconstruction.com/services', ownership: 'ESOP', ownershipUrl: 'https://www.escoconstruction.com/about-us', revenue: '$200M+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Long-running Idaho utility contractor', notesUrl: SHARED_SOURCES.enr, type: ['underground', 'heavy-civil'] },
    { name: 'Las Vegas Paving', nameUrl: 'https://www.lasvegaspaving.com', hq: 'Las Vegas, NV', hqUrl: 'https://www.lasvegaspaving.com/about', coverage: 'Nevada + Southwest', coverageUrl: 'https://www.lasvegaspaving.com/operations', segment: 'Roadway + civil', segmentUrl: 'https://www.lasvegaspaving.com', ownership: 'Private', ownershipUrl: 'https://www.lasvegaspaving.com/about', revenue: '$1B (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Large Nevada transportation contractor', notesUrl: SHARED_SOURCES.enr, type: ['heavy-civil'] }
];

var ESOP_COMPANIES = [
    { name: 'Sundt Construction', nameUrl: 'https://www.sundt.com', hq: 'Tempe, AZ', hqUrl: 'https://www.sundt.com/about/', coverage: 'Western U.S.', coverageUrl: 'https://www.sundt.com/locations/', segment: 'Civil + industrial + building', segmentUrl: 'https://www.sundt.com/services/', ownership: 'ESOP', ownershipUrl: 'https://www.sundt.com/about/', revenue: '$2B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Employee-owned since 1990', notesUrl: 'https://www.sundt.com/about/', type: ['gc', 'heavy-civil'] },
    { name: 'Achen-Gardner Construction', nameUrl: 'https://www.achengardner.com', hq: 'Maricopa, AZ', hqUrl: 'https://www.achengardner.com/about-us', coverage: 'Southwest U.S.', coverageUrl: 'https://www.achengardner.com/projects', segment: 'Underground utilities', segmentUrl: 'https://www.achengardner.com/services', ownership: 'ESOP', ownershipUrl: 'https://www.achengardner.com/about-us', revenue: '$300M+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Utility and waterline specialist', notesUrl: SHARED_SOURCES.enr, type: ['underground'] },
    { name: 'ESCO Construction', nameUrl: 'https://www.escoconstruction.com', hq: 'Meridian, ID', hqUrl: 'https://www.escoconstruction.com/about-us', coverage: 'Mountain West', coverageUrl: 'https://www.escoconstruction.com/projects', segment: 'Underground + heavy civil', segmentUrl: 'https://www.escoconstruction.com/services', ownership: 'ESOP', ownershipUrl: 'https://www.escoconstruction.com/about-us', revenue: '$200M+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Employee-owned since 1944 legacy', notesUrl: 'https://www.escoconstruction.com/about-us', type: ['underground', 'heavy-civil'] },
    { name: 'Hensel Phelps', nameUrl: 'https://www.henselphelps.com', hq: 'Greeley, CO', hqUrl: 'https://www.henselphelps.com/about/', coverage: 'National U.S.', coverageUrl: 'https://www.henselphelps.com/projects/', segment: 'General building + federal', segmentUrl: 'https://www.henselphelps.com/markets/', ownership: 'Employee-owned', ownershipUrl: 'https://www.henselphelps.com/careers/', revenue: '$5B+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Large employee-owned GC', notesUrl: SHARED_SOURCES.enr, type: ['gc'] }
];

var PUBLIC_COMPANIES = [
    { name: 'Quanta Services (PWR)', nameUrl: 'https://www.quantaservices.com', hq: 'Houston, TX', hqUrl: 'https://www.quantaservices.com/about', coverage: 'U.S. + Canada', coverageUrl: 'https://www.quantaservices.com/operations', segment: 'Utility + energy infrastructure', segmentUrl: 'https://www.quantaservices.com/services', ownership: 'Public', ownershipUrl: SHARED_SOURCES.sec, revenue: '$22.8B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PWR/quanta-services/revenue', notes: 'NYSE: PWR', notesUrl: SHARED_SOURCES.sec, type: ['heavy-civil', 'underground'] },
    { name: 'Fluor (FLR)', nameUrl: 'https://www.fluor.com', hq: 'Irving, TX', hqUrl: 'https://www.fluor.com/about-fluor', coverage: 'U.S. + global', coverageUrl: 'https://www.fluor.com/projects', segment: 'Industrial + infrastructure', segmentUrl: 'https://www.fluor.com/markets', ownership: 'Public', ownershipUrl: SHARED_SOURCES.sec, revenue: '$15.6B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/FLR/fluor/revenue', notes: 'NYSE: FLR', notesUrl: SHARED_SOURCES.sec, type: ['heavy-civil'] },
    { name: 'EMCOR Group (EME)', nameUrl: 'https://www.emcorgroup.com', hq: 'Norwalk, CT', hqUrl: 'https://www.emcorgroup.com/about-us/', coverage: 'U.S. + Canada', coverageUrl: 'https://www.emcorgroup.com/our-companies/', segment: 'MEP construction', segmentUrl: 'https://www.emcorgroup.com/services/', ownership: 'Public', ownershipUrl: SHARED_SOURCES.sec, revenue: '$14.6B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/EME/emcor-group/revenue', notes: 'NYSE: EME', notesUrl: SHARED_SOURCES.sec, type: ['gc'] },
    { name: 'Jacobs (J)', nameUrl: 'https://www.jacobs.com', hq: 'Dallas, TX', hqUrl: 'https://www.jacobs.com/about', coverage: 'U.S. + global', coverageUrl: 'https://www.jacobs.com/projects', segment: 'Infrastructure + CM', segmentUrl: 'https://www.jacobs.com/solutions', ownership: 'Public', ownershipUrl: SHARED_SOURCES.sec, revenue: '$11.5B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/J/jacobs-solutions/revenue', notes: 'NYSE: J', notesUrl: SHARED_SOURCES.sec, type: ['heavy-civil'] },
    { name: 'Primoris (PRIM)', nameUrl: 'https://www.primoriscorp.com', hq: 'Dallas, TX', hqUrl: 'https://www.primoriscorp.com/about/', coverage: 'United States', coverageUrl: 'https://www.primoriscorp.com/markets/', segment: 'Underground + utilities + civil', segmentUrl: 'https://www.primoriscorp.com/services/', ownership: 'Public', ownershipUrl: SHARED_SOURCES.sec, revenue: '$5.7B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PRIM/primoris-services/revenue', notes: 'NASDAQ: PRIM', notesUrl: SHARED_SOURCES.sec, type: ['underground'] },
    { name: 'Granite Construction (GVA)', nameUrl: 'https://www.graniteconstruction.com', hq: 'Watsonville, CA', hqUrl: 'https://www.graniteconstruction.com/about-us', coverage: 'United States', coverageUrl: 'https://www.graniteconstruction.com/locations', segment: 'Heavy civil + transportation', segmentUrl: 'https://www.graniteconstruction.com/services', ownership: 'Public', ownershipUrl: SHARED_SOURCES.sec, revenue: '$4.3B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/GVA/granite-construction/revenue', notes: 'NYSE: GVA', notesUrl: SHARED_SOURCES.sec, type: ['heavy-civil'] },
    { name: 'MYR Group (MYRG)', nameUrl: 'https://www.myrgroup.com', hq: 'Henderson, CO', hqUrl: 'https://www.myrgroup.com/about', coverage: 'United States', coverageUrl: 'https://www.myrgroup.com/our-companies', segment: 'Electrical + transmission', segmentUrl: 'https://www.myrgroup.com/services', ownership: 'Public', ownershipUrl: SHARED_SOURCES.sec, revenue: '$3.6B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/MYRG/myr-group/revenue', notes: 'NASDAQ: MYRG', notesUrl: SHARED_SOURCES.sec, type: ['underground'] }
];

var UNDERGROUND_COMPANIES = [
    { name: 'Primoris', nameUrl: 'https://www.primoriscorp.com', hq: 'Dallas, TX', hqUrl: 'https://www.primoriscorp.com/about/', coverage: 'National U.S.', coverageUrl: 'https://www.primoriscorp.com/markets/', segment: 'Pipeline + gas + utility', segmentUrl: 'https://www.primoriscorp.com/services/', ownership: 'Public (NASDAQ: PRIM)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$5.7B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PRIM/primoris-services/revenue', notes: 'Top underground utility benchmark', notesUrl: SHARED_SOURCES.enr, type: ['underground'] },
    { name: 'Quanta Services', nameUrl: 'https://www.quantaservices.com', hq: 'Houston, TX', hqUrl: 'https://www.quantaservices.com/about', coverage: 'North America', coverageUrl: 'https://www.quantaservices.com/operations', segment: 'Electric + gas + telecom underground', segmentUrl: 'https://www.quantaservices.com/services', ownership: 'Public (NYSE: PWR)', ownershipUrl: SHARED_SOURCES.sec, revenue: '$22.8B (2024)', revenueUrl: 'https://www.macrotrends.net/stocks/charts/PWR/quanta-services/revenue', notes: 'Largest utility infrastructure contractor', notesUrl: SHARED_SOURCES.enr, type: ['underground'] },
    { name: 'Achen-Gardner Construction', nameUrl: 'https://www.achengardner.com', hq: 'Maricopa, AZ', hqUrl: 'https://www.achengardner.com/about-us', coverage: 'Southwest U.S.', coverageUrl: 'https://www.achengardner.com/projects', segment: 'Water + sewer + storm drain', segmentUrl: 'https://www.achengardner.com/services', ownership: 'ESOP', ownershipUrl: 'https://www.achengardner.com/about-us', revenue: '$300M+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Specialized municipal underground contractor', notesUrl: SHARED_SOURCES.enr, type: ['underground'] },
    { name: 'ESCO Construction', nameUrl: 'https://www.escoconstruction.com', hq: 'Meridian, ID', hqUrl: 'https://www.escoconstruction.com/about-us', coverage: 'Mountain West', coverageUrl: 'https://www.escoconstruction.com/projects', segment: 'Underground + site civil', segmentUrl: 'https://www.escoconstruction.com/services', ownership: 'ESOP', ownershipUrl: 'https://www.escoconstruction.com/about-us', revenue: '$200M+ (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Long-run utility specialist', notesUrl: SHARED_SOURCES.enr, type: ['underground'] },
    { name: 'Wadsworth Brothers Construction', nameUrl: 'https://www.wadsworthbrothers.com', hq: 'Draper, UT', hqUrl: 'https://www.wadsworthbrothers.com/about', coverage: 'Utah + Intermountain West', coverageUrl: 'https://www.wadsworthbrothers.com/projects', segment: 'Culvert + storm + utility', segmentUrl: 'https://www.wadsworthbrothers.com/services', ownership: 'Private', ownershipUrl: 'https://www.wadsworthbrothers.com/about', revenue: '$200M-$400M (est.)', revenueUrl: SHARED_SOURCES.enr, notes: 'Utah-focused underground presence', notesUrl: SHARED_SOURCES.enr, type: ['underground', 'heavy-civil'] }
];

function escapeHtml(value) {
    return String(value || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function linkedCell(text, url) {
    var safeText = escapeHtml(text);
    if (!url) return safeText;
    return '<a href="' + escapeHtml(url) + '" target="_blank" rel="noopener">' + safeText + '</a>';
}

function renderCompanyTable(containerId, rows) {
    var container = document.getElementById(containerId);
    if (!container) return;

    container.innerHTML = '<div class="company-table-wrap">' +
        '<table class="company-table">' +
        '<thead><tr>' +
        '<th>Company</th>' +
        '<th>HQ</th>' +
        '<th>Coverage</th>' +
        '<th>Focus</th>' +
        '<th>Ownership</th>' +
        '<th>Revenue</th>' +
        '<th>Notes</th>' +
        '</tr></thead>' +
        '<tbody>' +
        rows.map(function(row) {
            var searchable = [
                row.name,
                row.hq,
                row.coverage,
                row.segment,
                row.ownership,
                row.revenue,
                row.notes
            ].join(' ').toLowerCase();

            return '<tr class="company-row" data-type="' + escapeHtml((row.type || []).join(' ')) + '" data-search="' + escapeHtml(searchable) + '">' +
                '<td>' + linkedCell(row.name, row.nameUrl) + '</td>' +
                '<td>' + linkedCell(row.hq, row.hqUrl) + '</td>' +
                '<td>' + linkedCell(row.coverage, row.coverageUrl) + '</td>' +
                '<td>' + linkedCell(row.segment, row.segmentUrl) + '</td>' +
                '<td>' + linkedCell(row.ownership, row.ownershipUrl) + '</td>' +
                '<td>' + linkedCell(row.revenue, row.revenueUrl) + '</td>' +
                '<td>' + linkedCell(row.notes, row.notesUrl) + '</td>' +
                '</tr>';
        }).join('') +
        '</tbody></table></div>';
}

function updateGridVisibility(grid) {
    if (!grid) return;
    var activeType = grid.dataset.activeType || 'all';
    var query = (grid.dataset.query || '').toLowerCase();
    grid.querySelectorAll('.company-row').forEach(function(row) {
        var typeMatch = (activeType === 'all') || row.dataset.type.includes(activeType);
        var searchMatch = !query || row.dataset.search.includes(query);
        row.style.display = (typeMatch && searchMatch) ? '' : 'none';
    });
}

function filterCompanies(gridId, type, btn) {
    var grid = document.getElementById(gridId + '-grid');
    if (!grid) return;
    grid.dataset.activeType = type;
    if (btn && btn.parentElement) {
        btn.parentElement.querySelectorAll('.co-filter').forEach(function(button) {
            button.classList.remove('active');
        });
        btn.classList.add('active');
    }
    updateGridVisibility(grid);
}

function bindCompanySearch() {
    document.querySelectorAll('.company-search').forEach(function(input) {
        var gridId = input.dataset.grid;
        var grid = document.getElementById(gridId);
        if (!grid) return;
        input.addEventListener('input', function() {
            grid.dataset.query = input.value.trim();
            updateGridVisibility(grid);
        });
    });
}

renderCompanyTable('na-grid', NORTH_AMERICA_LEADERS);
renderCompanyTable('us-grid', UNITED_STATES_LEADERS);
renderCompanyTable('state-grid', STATE_LEADERS);
renderCompanyTable('utah-grid', UTAH_COMPANIES);
renderCompanyTable('mw-grid', MW_COMPANIES);
renderCompanyTable('esop-grid', ESOP_COMPANIES);
renderCompanyTable('public-grid', PUBLIC_COMPANIES);
renderCompanyTable('underground-grid', UNDERGROUND_COMPANIES);
bindCompanySearch();
