"""
openmud Proposal Tools
Generate construction proposal HTML for PDF export.
"""

from typing import Optional


def render_proposal_html(
    client: str,
    scope: str,
    total: float,
    duration: Optional[int] = None,
    assumptions: Optional[str] = None,
    exclusions: Optional[str] = None,
) -> str:
    """
    Render proposal as HTML for PDF generation.

    Args:
        client: Client or project name
        scope: Scope of work description
        total: Total bid amount
        duration: Duration in days (optional)
        assumptions: Assumptions (optional)
        exclusions: Exclusions (optional)

    Returns:
        HTML string for PDF export
    """
    total_str = f"${int(total):,}" if total else "—"
    duration_str = f"<p style='margin:8px 0 0;'>Duration: {duration} days</p>" if duration else ""

    assumptions_block = ""
    if assumptions and assumptions.strip():
        assumptions_block = (
            f"<h2 style='font-size:1.1rem;margin:24px 0 8px;'>Assumptions</h2>"
            f"<p style='margin:0;line-height:1.6;'>{assumptions.strip().replace(chr(10), '<br>')}</p>"
        )

    exclusions_block = ""
    if exclusions and exclusions.strip():
        exclusions_block = (
            f"<h2 style='font-size:1.1rem;margin:24px 0 8px;'>Exclusions</h2>"
            f"<p style='margin:0;line-height:1.6;'>{exclusions.strip().replace(chr(10), '<br>')}</p>"
        )

    return (
        '<div class="pdf-doc" style="font-family:Merriweather,Georgia,serif;'
        'padding:40px;max-width:700px;margin:0 auto;">'
        "<h1 style='margin:0 0 8px;'>Proposal</h1>"
        f"<p style='color:#666;margin:0 0 24px;'>{client}</p>"
        "<h2 style='font-size:1.1rem;margin:24px 0 8px;'>Scope</h2>"
        f"<p style='margin:0;line-height:1.6;'>{(scope or '—').replace(chr(10), '<br>')}</p>"
        "<h2 style='font-size:1.1rem;margin:24px 0 8px;'>Pricing</h2>"
        f"<p style='margin:0;font-size:1.25rem;font-weight:700;'>{total_str}</p>"
        f"{duration_str}"
        f"{assumptions_block}"
        f"{exclusions_block}"
        "<p style='margin:32px 0 0;font-size:0.875rem;color:#666;'>Generated by openmud · openmud.ai</p>"
        "</div>"
    )
