/**
 * Proposal generation API - builds proposal HTML from estimate or manual inputs
 * Supports bid items (from estimate breakdown) for line-item proposals
 */

function buildProposal(params) {
  const {
    client = 'Project',
    scope = '',
    total = 0,
    duration = null,
    assumptions = '',
    exclusions = '',
    bid_items = [],
  } = params;

  const totalStr = total ? `$${Math.round(total).toLocaleString()}` : '—';
  const durationStr = duration ? `<p style='margin:8px 0 0;'>Duration: ${duration} days</p>` : '';

  let assumptionsBlock = '';
  if (assumptions && assumptions.trim()) {
    assumptionsBlock = `<h2 style='font-size:1.1rem;margin:24px 0 8px;color:#111;'>Assumptions</h2><p style='margin:0;line-height:1.6;color:#111;'>${assumptions.trim().replace(/\n/g, '<br>')}</p>`;
  }

  let exclusionsBlock = '';
  if (exclusions && exclusions.trim()) {
    exclusionsBlock = `<h2 style='font-size:1.1rem;margin:24px 0 8px;color:#111;'>Exclusions</h2><p style='margin:0;line-height:1.6;color:#111;'>${exclusions.trim().replace(/\n/g, '<br>')}</p>`;
  }

  let bidItemsBlock = '';
  if (Array.isArray(bid_items) && bid_items.length > 0) {
    let rows = bid_items
      .filter((item) => item && (item.description || item.amount != null))
      .map((item) => {
        const desc = (item.description || '').trim() || '—';
        const amt = item.amount != null ? `$${Math.round(item.amount).toLocaleString()}` : '—';
        return `<tr><td style='padding:8px 12px;border-bottom:1px solid #ddd;color:#111;'>${desc}</td><td style='padding:8px 12px;border-bottom:1px solid #ddd;text-align:right;color:#111;'>${amt}</td></tr>`;
      })
      .join('');
    bidItemsBlock = `<h2 style='font-size:1.1rem;margin:24px 0 8px;color:#111;'>Bid Items</h2><table style='width:100%;border-collapse:collapse;color:#111;'><thead><tr style='background:#f0f0f0;'><th style='padding:8px 12px;text-align:left;color:#111;'>Item</th><th style='padding:8px 12px;text-align:right;color:#111;'>Amount</th></tr></thead><tbody>${rows}</tbody></table><p style='margin:12px 0 0;font-size:1.1rem;font-weight:700;color:#111;'>Total: ${totalStr}</p>`;
  }

  const pricingBlock = bidItemsBlock || `<p style='margin:0;font-size:1.25rem;font-weight:700;color:#111;'>${totalStr}</p>${durationStr}`;

  const html = `<div class="pdf-doc" style="font-family:Merriweather,Georgia,serif;padding:40px;max-width:700px;margin:0 auto;background:#fff;color:#111;">
<h1 style='margin:0 0 8px;color:#111;'>Proposal</h1>
<p style='color:#666;margin:0 0 24px;'>${client}</p>
<h2 style='font-size:1.1rem;margin:24px 0 8px;color:#111;'>Scope</h2>
<p style='margin:0;line-height:1.6;color:#111;'>${(scope || '—').replace(/\n/g, '<br>')}</p>
<h2 style='font-size:1.1rem;margin:24px 0 8px;color:#111;'>Pricing</h2>
${pricingBlock}
${!bidItemsBlock ? durationStr : ''}
${assumptionsBlock}
${exclusionsBlock}
<p style='margin:32px 0 0;font-size:0.875rem;color:#666;'>Generated by openmud · openmud.ai</p>
</div>`;

  return { client, scope, total, duration, bid_items, html };
}

async function proposalHandler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const body = req.body || {};
    const result = buildProposal({
      client: body.client || body.client_name || 'Project',
      scope: body.scope || '',
      total: parseFloat(body.total) || 0,
      duration: body.duration != null ? parseInt(body.duration, 10) : null,
      assumptions: body.assumptions || '',
      exclusions: body.exclusions || '',
      bid_items: body.bid_items || [],
    });
    return res.status(200).json(result);
  } catch (err) {
    console.error('Proposal error:', err);
    return res.status(500).json({ error: err.message || 'Proposal generation failed' });
  }
}

proposalHandler.buildProposal = buildProposal;
module.exports = proposalHandler;
