/**
 * Schedule generation API - matches tools/schedule/schedule_tools.py
 * Returns schedule HTML for PDF generation (construction documents style)
 */
function buildSchedule(projectName, durationDays, startDate, phases) {
  const start = startDate ? new Date(startDate) : new Date();
  const duration = Math.max(1, parseInt(durationDays, 10) || 14);
  const phaseList = Array.isArray(phases) && phases.length > 0
    ? phases
    : ['Mobilization', 'Trenching', 'Pipe install', 'Backfill', 'Restoration'];
  const daysPerPhase = Math.max(1, Math.floor(duration / phaseList.length));
  const rows = [];
  let d = new Date(start);

  for (let i = 0; i < phaseList.length; i++) {
    const phaseDays = i === phaseList.length - 1
      ? duration - (phaseList.length - 1) * daysPerPhase
      : daysPerPhase;
    const end = new Date(d);
    end.setDate(end.getDate() + phaseDays - 1);
    rows.push({
      phase: phaseList[i],
      start: d.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' }),
      end: end.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' }),
      days: phaseDays,
    });
    d.setDate(d.getDate() + phaseDays);
  }

  let table = '<table style="width:100%;border-collapse:collapse;"><tr style="background:#f0f0f0;"><th style="padding:10px;text-align:left;">Phase</th><th>Start</th><th>End</th><th>Days</th></tr>';
  rows.forEach((r) => {
    table += `<tr><td style="padding:10px;border-bottom:1px solid #ddd;">${r.phase}</td><td style="padding:10px;border-bottom:1px solid #ddd;">${r.start}</td><td style="padding:10px;border-bottom:1px solid #ddd;">${r.end}</td><td style="padding:10px;border-bottom:1px solid #ddd;">${r.days}</td></tr>`;
  });
  table += '</table>';

  const html = `<div class="pdf-doc" style="font-family:Merriweather,Georgia,serif;padding:40px;max-width:700px;margin:0 auto;">
<h1 style="margin:0 0 8px;">Schedule</h1>
<p style="color:#666;margin:0 0 24px;">${projectName} · ${duration} days</p>
${table}
<p style="margin:24px 0 0;font-size:0.875rem;color:#666;">Generated by Rockmud · rockmud.com</p></div>`;

  return { project_name: projectName, duration, phases: rows, table_html: table, html };
}

async function scheduleHandler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { project_name, duration_days, start_date, phases } = req.body || {};
    const result = buildSchedule(
      project_name || 'Project',
      duration_days || 14,
      start_date || null,
      phases || null
    );
    return res.status(200).json(result);
  } catch (err) {
    console.error('Schedule error:', err);
    return res.status(500).json({ error: err.message || 'Schedule generation failed' });
  }
}

scheduleHandler.buildSchedule = buildSchedule;
module.exports = scheduleHandler;
